<a href="https://colab.research.google.com/github/Kashialy/Eda-project-new/blob/main/ML_project_part_1_kashif.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Step 1 : import library
import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np

In [5]:
df=pd.read_csv('/content/drive/MyDrive/Classroom/DS Bootcamp Cohort 11/StudentsPerformance.csv')
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72         

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
#import sklearn liberary for one hot encoded data
from sklearn.preprocessing import OneHotEncoder
one_hot_encoded_data = pd.get_dummies(df, columns = ['gender','race/ethnicity','parental level of education','lunch','test preparation course'])
print(one_hot_encoded_data)

     math score  reading score  writing score  gender_female  gender_male  \
0            72             72             74           True        False   
1            69             90             88           True        False   
2            90             95             93           True        False   
3            47             57             44          False         True   
4            76             78             75          False         True   
..          ...            ...            ...            ...          ...   
995          88             99             95           True        False   
996          62             55             55          False         True   
997          59             71             65           True        False   
998          68             78             77           True        False   
999          77             86             86           True        False   

     race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(one_hot_encoded_data[['math score','reading score','writing score']])
print(scaled_data)

[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 ...
 [-0.46775108  0.12547206 -0.20107904]
 [ 0.12609287  0.60515772  0.58901542]
 [ 0.71993682  1.15336989  1.18158627]]


In [ ]:
combined_data = pd.concat([one_hot_encoded_data, pd.DataFrame(scaled_data, columns=['math score (scaled)', 'reading score (scaled)', 'writing score (scaled)'])], axis=1)
# Print the head of the combined data to verify
print(combined_data.head())

   math score  reading score  writing score  gender_female  gender_male  \
0          72             72             74           True        False   
1          69             90             88           True        False   
2          90             95             93           True        False   
3          47             57             44          False         True   
4          76             78             75          False         True   

   race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                   False                    True                   False   
1                   False                   False                    True   
2                   False                    True                   False   
3                    True                   False                   False   
4                   False                   False                    True   

   race/ethnicity_group D  race/ethnicity_group E  ...  \
0                   False   

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error

In [9]:
#predict math score


features=['gender','race/ethnicity','parental level of education','lunch','test preparation course','math score','reading score','writing score']
target=['math score']
X=df[features]
y=df[[target]]

KeyError: "None of [Index([('math score',)], dtype='object')] are in the [columns]"

In [15]:
from math import remainder
#apply one_hot encoding to categorical columns
categorical_columns=['gender','race/ethnicity','parental level of education','lunch','test preparation course']
numerical_columns=['math score','reading score','writing score']

#apply one hot encoding to categorical value
X_encoded_categorical=pd.get_dummies(X,columns=categorical_columns,drop_first=True)
X_numerical=X[numerical_columns]
X_processed=pd.concat([X_encoded_categorical,X_numerical],axis=1)

In [16]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8, random_state=42)

In [17]:

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 8), (200, 8), (800,), (200,))

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ValueError: could not convert string to float: 'female'

In [ ]:
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

ValueError: could not convert string to float: 'female'

In [ ]:
# Step 5 : select model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test) #model shouldn't know anything about the test data so only transform

ValueError: could not convert string to float: 'female'

In [ ]:
# Step 6 : train or fit model
model.fit(X_train,y_train)

ValueError: could not convert string to float: 'female'

In [ ]:
y_pred =model.predict(X_test)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
mean_absolute_error(y_test, y_pred)

NameError: name 'y_pred' is not defined

In [24]:
mean_squared_error(y_test, y_pred)

NameError: name 'y_pred' is not defined

In [21]:
r2=r2_score(y_test, y_pred)
print("R_squared:",r2)

NameError: name 'r2_score' is not defined

In [ ]:
plt.scatter(y_test, y_pred_linear, color=blue, label="Linear Regression")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.title("Actual vs Predicted Values")
plt.show()